site_name: CypherQuest FAQ
site_url: https://faq.cypherquest.ai
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - header.autohide

  icon:
    repo: fontawesome/brands/github
    logo: material/library

# Repository
repo_name: ankh2054/wax_puzzle
repo_url: https://github.com/ankh2054/wax_puzzle

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ankh2054
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bit90studios

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
nav:
  - Home: index.md
  - FAQ: faq.md

extra_css:
  - stylesheets/extra.css

