version: '3.8'

services:
  landing-page:
    container_name: landing-page
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VIRTUAL_HOST=www.cypherquest.ai,cypherquest.ai
      - LETSENCRYPT_HOST=www.cypherquest.ai,cypherquest.ai
      - LETSENCRYPT_EMAIL=charles.holtzkampf@gmail.com
    networks:
      - sentnl-net

networks:
  sentnl-net:
    external: true 